# Prebuilt base image with jetpack, pytorch and ros2 humble.
FROM abmorobotics/aau_rover_ros_base:humble

ENV DEBIAN_FRONTEND noninteractive

# Args
ARG ROVER_REPO_NAME=isaac_rover_physical_2.0
ARG BASE_FOLDER=/home/orin/Documents


# Install utils
RUN apt-get update && apt-get install nano && apt-get install iputils-ping
# Install tools for canbus
RUN apt-get install busybox && apt-get install iproute2 -y
RUN apt-get install -y --no-install-recommends zstd wget less cmake curl gnupg2 \
    build-essential python3 python3-pip python3-dev python3-setuptools libusb-1.0-0-dev -y 
RUN apt-get install libspnav-dev
RUN apt-get install libbluetooth-dev
RUN apt install libcwiid-dev
# PIP packages
RUN pip3 install grpcio==1.58.0
RUN pip3 install skrl["torch"]
RUN pip3 install Jetson.GPIO
RUN pip3 install onnx
RUN pip3 install canopen
RUN pip3 install numpy --upgrade
RUN pip3 install protobuf 

# Install the ZED SDK
ARG ZED_SDK_MAJOR=4
ARG ZED_SDK_MINOR=0
ARG ZED_SDK_PATCH=5
ARG L4T_MAJOR=35
ARG L4T_MINOR=3

RUN echo "# R${L4T_MAJOR} (release), REVISION: ${L4T_MINOR}" > /etc/nv_tegra_release && \
    apt-get update -y || true && \
    wget -q --no-check-certificate -O ZED_SDK_Linux_JP.run \
    https://download.stereolabs.com/zedsdk/${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}/l4t${L4T_MAJOR}.${L4T_MINOR}/jetsons && \
    chmod +x ZED_SDK_Linux_JP.run ; ./ZED_SDK_Linux_JP.run silent skip_tools && \
    rm -rf /usr/local/zed/resources/* && \
    rm -rf ZED_SDK_Linux_JP.run && \
    rm -rf /var/lib/apt/lists/*

RUN python3 /usr/local/zed/get_python_api.py

# #This symbolic link is needed to use the streaming features on Jetson inside a container
RUN ln -sf /usr/lib/aarch64-linux-gnu/tegra/libv4l2.so.0 /usr/lib/aarch64-linux-gnu/libv4l2.so

# Change this repo later
RUN git clone https://github.com/abmoRobotics/${ROVER_REPO_NAME}.git ${BASE_FOLDER}/${ROVER_REPO_NAME}

# Build the rover
RUN /bin/bash -c "source /opt/ros/humble/install/setup.bash && cd ${BASE_FOLDER}/${ROVER_REPO_NAME} && colcon build"

#RUN apt-get update && apt-get install -y ros-humble-joy* && rm -rf /var/lib/apt/lists/*

RUN cd ${BASE_FOLDER}/isaac_rover_physical_2.0/src && git clone https://github.com/ros-drivers/joystick_drivers.git && cd joystick_drivers && git checkout remotes/origin/humble-devel

# These are bugged and not needed for the project as for now
RUN cd ${BASE_FOLDER}/isaac_rover_physical_2.0/src/joystick_drivers && rm -rf spacenav && rm -rf wiimote && rm -rf wiimote_msgs 

RUN cd ${BASE_FOLDER}/isaac_rover_physical_2.0/src && git clone https://github.com/ros/diagnostics.git && cd diagnostics && git checkout remotes/origin/stale/humble
RUN /bin/bash -c "cd ${BASE_FOLDER}/isaac_rover_physical_2.0 && source /opt/ros/humble/install/setup.bash && cd ${BASE_FOLDER}/${ROVER_REPO_NAME} && colcon build"
WORKDIR ${BASE_FOLDER}/${ROVER_REPO_NAME}
RUN echo "source /opt/ros/humble/install/setup.bash" >> ~/.bashrc
RUN echo "source ${BASE_FOLDER}/${ROVER_REPO_NAME}/install/setup.bash" >> ~/.bashrc


# Copy the entrypoint script into the container
COPY entrypoint.sh /entrypoint.sh

# Set the entrypoint script as the entry point for the container
ENTRYPOINT ["/entrypoint.sh"]









